version: "3.7"
services:
  database:
    image: mongo:6.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=zenn_internal
      - MONGO_INITDB_USERNAME=admin 
      - MONGO_INITDB_PASSWORD=1234
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
networks:
  default:
    name: local
    external: true
